# https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
kind: Service
apiVersion: v1
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  ports:
    - port: 5000
  selector:
    app: gateway
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - image: denporras/soa_api_gateway
          name: gateway
          ports:
            - containerPort: 5000
          stdin: true


