# https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
kind: Service
apiVersion: v1
metadata:
  name: products-node
  labels:
    app: products-node
spec:
  ports:
    - port: 7000
  selector:
    app: products-node
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-node
  labels:
    app: products-node
spec:
  selector:
    matchLabels:
      app: products-node
  replicas: 2
  template:
    metadata:
      labels:
        app: products-node
    spec:
      containers:
        - image: denporras/soa_catalog_node
          name: products
          ports:
            - containerPort: 7000
          stdin: true


